spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: Sova1029
        url: jdbc:postgresql://localhost/Project
        username: postgres
    freemarker:
        expose-request-attributes: true
    jpa:
        generate-ddl: true
    main:
        allow-circular-references: true

    liquibase:
        change-log: classpath:liquibase/liquibase-outputChangeLog.xml
springdoc:
    swagger-ui:
        path: /swagger-ui.html