<#import "parts/common.ftlh" as c>
<@c.page>

    <h1>Main page</h1>
    <h5>Hello, Roleplayer</h5>
    <div>This is our official DiceHead website!</div>
    <img src="https://sun9-53.userapi.com/impg/c857328/v857328805/1ef16d/Xk8gMPD6GaQ.jpg?size=762x1080&quality=96&sign=820d160d8ac21caa6df32fc865f617dd&type=album"
         width="220" height="300">

    <br><h5>Check our social networks:</h5>

    <p> <img src="https://play-lh.googleusercontent.com/GntsGclzheXXASOhjSF1lCOPOznM_OARDObiTW_NQZtpYVwPQr_0ARyRyiXB0_OocmI" width="25" height="25">
        <a href="https://vk.com/dicehead_dnd" target="_blank">VK</a></p>
    <p> <img src="https://yt3.ggpht.com/ytc/AKedOLTxbphuw9Aq7H8iBIt2cEAmTjo4J9jJR2O5rPeiTQ=s900-c-k-c0x00ffffff-no-rj" width="25" height="25">
        <a href="https://www.youtube.com/c/DiceHead" target="_blank">YouTube</a></p>
    <p> <img src="https://play-lh.googleusercontent.com/h9jWMwqb-h9hjP4THqrJ50eIwPekjv7QPmTpA85gFQ10PjV02CoGAcYLLptqd19Sa1iJ " width="25" height="25">
        <a href="https://www.instagram.com/dicehead.off/" target="_blank">Instagram</a></p>
    <p> <img src="https://play-lh.googleusercontent.com/Wvjx6rVlC1rGWKkln3r-23ICKV--sxEEUuq7jd15BeJan8v-wS7TGwm0NHXqqon18w" width="25" height="25">
        <a href="https://discord.gg/gDPxN7t6QH" target="_blank">Discord</a></p>


</@c.page>



