<#import "parts/common.ftlh" as c>
<#import "parts/login.ftlh" as l>
<@c.page>

    <h1>Main page</h1>

    <h5>Check our social networks</h5>

    <p><a href="https://vk.com/dicehead_dnd" target="_blank">VK</a></p>
    <p><a href="https://www.youtube.com/c/DiceHead" target="_blank">YouTube</a></p>
    <p><a href="https://www.instagram.com/dicehead.off/" target="_blank">Instagram</a></p>
    <p><a href="https://discord.gg/gDPxN7t6QH" target="_blank">Discord</a></p>


</@c.page>

